services:
  postgres:
    image: postgres:latest
    volumes:
      - ./pg-data/:/var/lib/postgresql/data
      - ./pg-dumps/:/home/dumps
    ports:
     - "5432:5432"
    environment:
      - POSTGRES_USER=mundolunar
      - POSTGRES_DB=mundolunar
      - POSTGRES_PASSWORD=abc123