# Generated by Django 4.0.2 on 2022-02-17 22:22

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mundolunar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='songpage',
            options={'verbose_name': 'song'},
        ),
        migrations.AddField(
            model_name='songpage',
            name='song_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='songpage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='textpage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
