# Generated by Django 4.0.2 on 2022-03-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mundolunar', '0004_alter_songpage_autoria_alter_songpage_data_gravacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='songpage',
            name='is_destaque',
            field=models.BooleanField(default=False),
        ),
    ]
