# Generated by Django 4.0.2 on 2024-02-05 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mundolunar', '0005_songpage_is_destaque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songpage',
            name='is_destaque',
            field=models.BooleanField(default=False, verbose_name='Destaque'),
        ),
    ]
